[tool.black]
line-length = 110
skip-string-normalization = true

[tool.pyright]
include = [
    "main.py",
    "srfvirus_spotify",
]
exclude = [
    "**/__pycache__",
    "build",
    "dist",
]
reportUnnecessaryTypeIgnoreComment = "warning"
reportUnusedImport = "error"
pythonVersion = "3.9"
typeCheckingMode = "basic"
